on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true
      - name: run tests
        # currently we only run git tests. list mostly taken from platform/testFramework/testResources/tests/testGroups.properties
        # TODO: figure out what other tests we should run
        run: |
          ./tests.cmd -Dintellij.build.test.patterns="git4idea.*;-git4idea.remote.GitRemoteTest;com.intellij.openapi.vcs.*;com.intellij.testFramework.vcs.*;com.intellij.tasks.vcs.*;com.intellij.vcs.*"
